apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.apiReplicaCount }}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: soluto/tweek-api:1.0.0-rc1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
        env:
        - name: PUBLIC_KEY_PATH
          value: /run/secrets/tweek-secrets/tweek_pfx_public_key
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Redis__ConnectionString
          value: redis
        - name: UseAddon__Rules
          value: MinioRules
        - name: RulesetVersionProvider
          value: NatsVersionProvider
        - name: Rules__Nats__Endpoint
          value: nats://nats:4222
        - name: Rules__Minio__Endpoint
          value: minio:9000
        - name: Rules__Minio__AccessKey
          value: AKIAIOSFODNN7EXAMPLE
        - name: Rules__Minio__SecretKey
          valueFrom:
            secretKeyRef:
              name: tweek-secrets
              key: minio_secret_key
        volumeMounts:
        - name: tweek-secrets
          mountPath: /run/secrets/tweek-secrets
      volumes:
        - name: tweek-secrets
          secret:
            secretName: tweek-secrets
            defaultMode: 0600
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api

{{- if .Values.apiAutoscaling.enabled -}}
---
kind: autoscaling/v2beta2
apiVersion: autoscaling/v2beta2
metadata:
  name: apihpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: api
  minReplicas: {{ .Values.apiAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiAutoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.apiAutoscaling.targetAverageUtilization }}
{{- end -}}