kind: ConfigMap
apiVersion: v1
metadata:
  name: gatewayconfig
data:
  gateway.json: |
    {
        "upstreams": {
            "api": "http://api",
            "authoring": "http://authoring:3000",
            "publishing": "http://publishing",
            "editor": "http://editor:3000"
        },
        "security": {
            "auth": {
                "providers": {},
                "basic_auth": {
                  "redirect_urls": [
                    "http{{ if $.Values.ingress.tls }}s{{ end }}://{{ .Values.domain }}"
                  ]
                }
            }
        },
        "v1Hosts": {
            "api": [
            ],
            "authoring": [
            ]
        }
    }
  gateway.k8s.json: {{ .Values.gatewayJson }}
