apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweek-gateway-{{ .Release.Name }}
spec:
  replicas: {{ .Values.gatewayReplicaCount }}
  selector:
    matchLabels:
      app: tweek-gateway-{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gateway-configmap.yaml") . | sha256sum }}
      labels:
        app: tweek-gateway-{{ .Release.Name }}
    spec:
      containers:
      - name: gateway
        image: soluto/tweek-gateway:{{ .Values.imageVersions.gateway }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 2G
        env:
        - name: TWEEKGATEWAY_SECURITY_CORS_ENABLED
          value: "true"
        - name: TWEEKGATEWAY_SECURITY_CORS_MAXAGE
          value: "60"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS
          value: "['*']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS
          value: "['GET','POST','PUT','PATCH','DELETE']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS
          value: "['*']"        
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT
          value: {{ include "minio.endpoint" . }}
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME
          value: tweek
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY
          value: {{ .Values.minio.accessKey }}
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY
          valueFrom:
            secretKeyRef:
              name: tweek-secrets-{{ .Release.Name }}
              key: minio_secret_key
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE
          value: "false"
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT
          value: nats://tweek-nats-{{ .Release.Name }}:4222
        - name: TWEEKGATEWAY_SECURITY_TWEEKSECRETKEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_private_key
        - name: TWEEKGATEWAY_CONFIGFILEPATH
          value: /config/gateway.json
        - name: CONFIGOR_ENV
          value: k8s
        volumeMounts:
        - name: tweek-secrets-{{ .Release.Name }}
          mountPath: /run/secrets/tweek-secrets
        - name: tweek-gatewayconfig-{{ .Release.Name }}
          mountPath: /config
      volumes:
        - name: tweek-secrets-{{ .Release.Name }}
          secret:
            secretName: tweek-secrets-{{ .Release.Name }}
            defaultMode: 0600
        - name: tweek-gatewayconfig-{{ .Release.Name }}
          configMap:
            name: tweek-gatewayconfig-{{ .Release.Name }}
---
kind: Service
apiVersion: v1
metadata:
  name: tweek-gateway-{{ .Release.Name }}
spec:
  selector:
    app: tweek-gateway-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tweek-gateway-pdb-{{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tweek-gateway-{{ .Release.Name }}
---
{{- if .Values.gatewayAutoscaling.enabled -}}
kind: autoscaling/v2beta2
apiVersion: autoscaling/v2beta2
metadata:
  name: tweek-gatewayhpa-{{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: tweek-gateway-{{ .Release.Name }}
  minReplicas: {{ .Values.gatwayAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.gatwayAutoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.gatewayAutoscaling.targetAverageUtilization }}
{{- end -}}