kind: ConfigMap
apiVersion: v1
metadata:
  name: tweek-gatewayconfig-{{ .Release.Name }}
data:
  gateway.json: |
    {
        "upstreams": {
            "api": "http://tweek-api-{{ .Release.Name }}",
            "authoring": "http://tweek-authoring-{{ .Release.Name }}:3000",
            "publishing": "http://tweek-publishing-{{ .Release.Name }}",
            "editor": "http://tweek-editor-{{ .Release.Name }}:3000"
        },
        "security": {
            "auth": {
                "providers": {},
                "basic_auth": {
                  "redirect_urls": [
                    "http{{ if $.Values.ingress.tls }}s{{ end }}://{{ .Values.domain }}"
                  ]
                }
            }
        },
        "v1Hosts": {
            "api": [
            ],
            "authoring": [
            ]
        }
    }
  gateway.k8s.json: {{ toJson .Values.gatewayJson | quote }}
