apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ template "tweek.namespace" }}
  name: gateway
spec:
  replicas: {{ .Values.gatewayReplicaCount }}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: soluto/tweek-gateway
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
        env:
        - name: TWEEKGATEWAY_SECURITY_CORS_ENABLED
          value: "true"
        - name: TWEEKGATEWAY_SECURITY_CORS_MAXAGE
          value: "60"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDORIGINS
          value: "['*']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDMETHODS
          value: "['GET','POST','PUT','PATCH','DELETE']"
        - name: TWEEKGATEWAY_SECURITY_CORS_ALLOWEDHEADERS
          value: "['*']"        
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOENDPOINT
          value: minio:9000
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOBUCKETNAME
          value: tweek
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOACCESSKEY
          value: AKIAIOSFODNN7EXAMPLE
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECRETKEY
          value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_MINIOSECURE
          value: "false"
        - name: TWEEKGATEWAY_SECURITY_POLICYSTORAGE_NATSENDPOINT
          value: nats://nats:4222
        - name: TWEEKGATEWAY_SECURITY_TWEEKSECRETKEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_private_key
        - name: TWEEKGATEWAY_CONFIGFILEPATH
          value: /config/gateway.json
        - name: CONFIGOR_ENV
          value: k8s
        volumeMounts:
        - name: tweek-secrets
          mountPath: /run/secrets/tweek-secrets
        - name: gatewayconfig
          mountPath: /config
      volumes:
        - name: tweek-secrets
          secret:
            secretName: tweek-secrets
            defaultMode: 0600
        - name: gatewayconfig
          configMap:
            name: gatewayconfig
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ template "tweek.namespace" }}
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gatewayconfig
  namespace: {{ template "tweek.namespace" }}
data:
  gateway.json: |
    {
        "upstreams": {
            "api": "http://api",
            "authoring": "http://authoring:3000",
            "publishing": "http://publishing",
            "editor": "http://editor:3000"
        },
        "security": {
            "auth": {
                "providers": {},
                "basic_auth": {
                  "redirect_urls": [
                    "http://{{ .Values.domain }}"
                  ]
                }
            }
        },
        "v1Hosts": {
            "api": [
            ],
            "authoring": [
            ]
        }
    }
gateway.k8s.json: {{ .Values.gatewayJson }}