apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: tweek-bare-repo
        image: soluto/tweek-bare-repo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        env:
        - name: PUBLIC_KEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_public_key
        volumeMounts:
        - name: tweek-secrets
          mountPath: /run/secrets/tweek-secrets
        - name: gitvolume
          mountPath: /tweek/repodata
      initContainers:
      - name: volume-initializer
        image: alpine/git
        command: [ "/bin/sh", "-c",
          "cd /tweek/repodata ; if ! git status ; then git init --bare ; chown -R 1000:1000 . ; fi"
        ]
        volumeMounts:
        - name: gitvolume
          mountPath: /tweek/repodata
      volumes:
        - name: tweek-secrets
          secret:
            secretName: tweek-secrets
        - name: gitvolume
          persistentVolumeClaim:
            claimName: gitvolume
---
kind: Service
apiVersion: v1
metadata:
  name: git
spec:
  selector:
    app: git
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitvolume.size }}
  storageClassName: {{ .Values.gitvolume.storageClass }}