apiVersion: v1
kind: Secret
metadata:
  name: tweek-secrets-{{ .Release.Name }}
data:
  tweek_pfx_public_key: {{ .Values.keys.tweek_pfx_public_key }}
  tweek_ssh_public_key: {{ .Values.keys.tweek_ssh_public_key }}
  tweek_ssh_private_key: {{ .Values.keys.tweek_ssh_private_key }}
  minio_secret_key: {{ b64enc .Values.minio.secretKey }}
---
{{- if eq .Values.redis.endpoint "" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweek-redis-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweek-redis-{{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: redis
        image: bitnami/redis
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: tweek-dbvolume-{{ .Release.Name }}
      volumes:
      - name: tweek-dbvolume-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: tweek-dbvolume-{{ .Release.Name }}
---
kind: Service
apiVersion: v1
metadata:
  name: tweek-redis-{{ .Release.Name }}
spec:
  selector:
    app: tweek-redis-{{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tweek-dbvolume-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbvolume.size }}
  storageClassName: {{ .Values.dbvolume.storageClass }}
---
{{- end -}}

{{- if eq .Values.minio.endpoint "" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweek-minio-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweek-minio-{{ .Release.Name }}
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.minio.accessKey }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tweek-secrets-{{ .Release.Name }}
              key: minio_secret_key
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 1G
---
kind: Service
apiVersion: v1
metadata:
  name: tweek-minio-{{ .Release.Name }}
spec:
  selector:
    app: tweek-minio-{{ .Release.Name }}
  ports:
    - port: 9000
      targetPort: 9000
---
{{- end -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweek-nats-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweek-nats-{{ .Release.Name }}
    spec:
      containers:
      - name: nats
        image: nats:1.0.4-linux
        ports:
        - containerPort: 4222
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
kind: Service
apiVersion: v1
metadata:
  name: tweek-nats-{{ .Release.Name }}
spec:
  selector:
    app: tweek-nats-{{ .Release.Name }}
  ports:
    - port: 4222
      targetPort: 4222
---

{{- if eq .Values.gitRepo "" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweek-git-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweek-git-{{ .Release.Name }}
    spec:
      containers:
      - name: tweek-bare-repo
        image: soluto/tweek-bare-repo:{{ .Values.imageVersions.git }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: PUBLIC_KEY_PATH
          value: /run/secrets/tweek-secrets/tweek_ssh_public_key
        volumeMounts:
        - name: tweek-secrets-{{ .Release.Name }}
          mountPath: /run/secrets/tweek-secrets
        - name: tweek-gitvolume-{{ .Release.Name }}
          mountPath: /tweek/repodata
      initContainers:
      - name: volume-initializer
        image: alpine/git
        command: [ "/bin/sh", "-c",
          "cd /tweek/repodata ; if ! git status ; then git init --bare ; chown -R 1000:1000 . ; fi"
        ]
        volumeMounts:
        - name: tweek-gitvolume-{{ .Release.Name }}
          mountPath: /tweek/repodata
      volumes:
        - name: tweek-secrets-{{ .Release.Name }}
          secret:
            secretName: tweek-secrets-{{ .Release.Name }}
        - name: tweek-gitvolume-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: tweek-gitvolume-{{ .Release.Name }}
---
kind: Service
apiVersion: v1
metadata:
  name: tweek-git-{{ .Release.Name }}
spec:
  selector:
    app: tweek-git-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tweek-gitvolume-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitvolume.size }}
  storageClassName: {{ .Values.gitvolume.storageClass }}
{{- end -}}