{{- if .Values.ingress.enabled -}}
{{- $fullName := include "tweek.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "tweek.name" . }}
    chart: {{ template "tweek.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: tweek-gateway-{{ .Release.Name }}
              servicePort: 80
{{- end }}
